# Generated by Django 4.1.2 on 2022-10-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveSmallIntegerField(verbose_name='Kilometraje')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('cost', models.PositiveIntegerField(verbose_name='Costo')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
            },
        ),
    ]
